name: sms_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  telephony: ^0.2.0
  permission_handler: ^12.0.0+1
  flutter_pdfview: ^1.4.0+1
  path_provider: ^2.1.5
  platform: ^3.1.6
  device_info_plus: ^11.4.0
  phone_state: ^2.1.1
  intl: ^0.20.2
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"  # Ensure the correct path here
  android_icon: "G-Alert"
  remove_alpha_ios: true  # Optional: removes alpha for iOS App Store
  web: false  # Disable web icon generation
  windows: false  # Disable Windows icon generation
  macos: false  # Disable macOS icon generation

flutter:
  assets:
    - assets/manual.pdf
    - assets/icon/  # Include the icon folder to be accessible in Flutter

  uses-material-design: true
